version: '3.2'

services:
  web:
    container_name: entries_app
    build: ./docker/web
    volumes:
      - type: bind
        source: .
        target: /var/www/sites/entries.com
    working_dir: /var/www/sites/entries.com
    ports:
      - 8085:80
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db
    networks:
      sites_network:
        ipv4_address: ${IPV4_NETWORK:-172.25.2}.30
        aliases:
          - litespeed

  db:
    container_name: entries_app_db
    build: ./docker/mysql
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql/
    env_file:
      - ./docker/mysql/env
    networks:
      sites_network:
        ipv4_address: ${IPV4_NETWORK:-172.25.2}.10
        aliases:
          - mysql

volumes:
  data:
    driver: "local"

networks:
  sites_network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.25.2}.0/24
